### ISSUE TITLE
Error running on version 2.8.7.8 but not on 2.8.7.7

### ISSUE THREAD

**Issue by sdtemple** [YingZhou001/IBDkin#5]
Hi Joe,

I am using IBD segments from hap-IBD and ibd-ends to infer kinship. I do use the --outmask and --outcoverage flags. I find that my command fails with the 2.8.7.8 version but not with the 2.8.7.7 version. I am more than happy to email you at your new address with some files to help you troubleshoot this.

Note that the 2.8.7.8 fails at the STDERR output "duplicated individuals:". I do believe there are duplicates in my sample.

Best,
Seth

**Comment by YingZhou001** [comment]
Hi Seth,

I am on traveling and I cannot work on this till the end of this Month.
Please do email me those files to ***@***.***

I will let you know when I start working on it.

Thank you,
Ying

**Comment by sdtemple** [comment]
No worries at all on the delay. I just wanted to give you a heads up. I will continue using 2.8.7.7 version for the time being, and email you my outputs. Have nice travels!

**Comment by YingZhou001** [comment]
Thanks!

**Comment by sdtemple** [comment]
Hi Ying, 

Circling back. I tried to send you my error message files to your old uw email address and through the Browing group Slack.

Best,
Seth

**Comment by YingZhou001** [comment]
Hi Seth,

Sorry to get you back late. I received your email and I will look into the issue later this week.

Best,
Ying

**Comment by sdtemple** [comment]
No worries at all. Work at your own pace! IBDKin is not a major part of the analysis I am working on. I just wanted to let you know so that you can fix the bug and make this great relatedness inference software available for other users. :)

**Comment by YingZhou001** [comment]
Hi Seth,

I believed this is my program bug. I downsize the mem for storing ID strings.  Could you help test it by adjusting the some parameters in the file "head.h"

Try to change the line17 
"#define BUFF_id 32 //for ID/Chr string length"    
into
"#define BUFF_id 128 //for ID/Chr string length" 

Thanks,
Ying

**Comment by sdtemple** [comment]
Hi Ying,

I apologize that it took me a little longer to respond to this. You are correct. I had identifiers with very long string names. Your suggestion has solved my issue. I changed 32 to 128 and then I use the command "make" to rebuild the program.

Thanks,
Seth
